### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by 11qu1d** [Spyduck/voxwriter#1]
Hi, 

After installing the plugin and try to do an export i receive the following error:

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voxwriter\__init__.py", line 61, in execute
    voxelize(context.active_object, self.filepath, vox_detail=max(0,min(126,self.voxel_detail)), use_default_palette=self.use_default_palette)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\voxwriter\writer.py", line 169, in voxelize
    source_name = obj.name
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
```

I am using Blender v.2.83.5 on Windows 10.

Thanks

**Comment by Spyduck** [comment]
Have you selected an object before export? If not, you'll need to choose an object (or select several and "join" before you export)

**Comment by 11qu1d** [comment]
Ah, sorry completely my fault. Thank you for your help.
