### ISSUE TITLE
Trying to convert GLTF to .vox and Running into Error

### ISSUE THREAD

**Issue by liowalex** [Spyduck/voxwriter#13]
Specs: Max OSX Catalina

error message: 
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect

StackTrace:
Converting to vox
Python: Traceback (most recent call last):
  File "/Users/aliow/Library/Application Support/Blender/3.0/scripts/addons/voxwriter/__init__.py", line 61, in execute
    voxelize(context.active_object, self.filepath, vox_detail=max(0,min(126,self.voxel_detail)), use_default_palette=self.use_default_palette)
  File "/Users/aliow/Library/Application Support/Blender/3.0/scripts/addons/voxwriter/writer.py", line 177, in voxelize
    bpy.ops.object.convert(target='MESH')
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect

**Comment by dulev** [comment]
This also happens for me on Windows.
