### ISSUE TITLE
An error occurred in the conversion

### ISSUE THREAD

**Issue by JXAFK** [Spyduck/voxwriter#14]
blender shows the following error: Python: Traceback (most recent call last):
  File "C:\Users\27296\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\voxwriter\__init__.py", line 59, in execute
    from .writer import voxelize
  File "C:\Users\27296\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\voxwriter\writer.py", line 7, in <module>
    from pyvox.models import Vox, Color, get_default_palette
ModuleNotFoundError: No module named 'pyvox'

**Comment by nicu-chiciuc** [comment]
Same issue here.

**Comment by nowaythisworks** [comment]
Fix: Instead of downloading the latest release, download the source contents (from the Code page) and install that. The latest release doesn't include the pyvox library.
